// Definición de temas disponibles
const themes = ["economia", "pareja", "ciencia", "psicologia", "religion", "politica", "desarrollo", "filosofia", "tecnologia", "historia", "historias-personales", "miedos", "amor", "educacion", "negocios"];

// Definición de preguntas por tema
const questions = {
    economia: [
    "1. ¿Cómo crees que la automatización y la inteligencia artificial afectarán el mercado laboral en los próximos años?",
    "2. Desde tu perspectiva, ¿cuál es el papel de la educación financiera en la toma de decisiones económicas personales?",
    "3. ¿Qué medidas propondrías para fomentar la inclusión financiera en comunidades con bajos recursos?",
    "4. ¿Cuál es tu visión sobre el papel del gobierno en la regulación económica?",
    "5. En tu opinión, ¿cómo pueden las empresas contribuir de manera más efectiva al desarrollo sostenible?",
    "6. ¿Qué medidas propones para abordar la brecha salarial de género en el ámbito laboral?",
    "7. ¿Cómo influye la educación en la movilidad económica de las personas?",
    "8. ¿Cuáles son los desafíos económicos específicos que enfrenta tu comunidad?",
    "9. ¿Qué importancia le das al comercio justo y cómo puede impactar positivamente en la economía global?",
    "10. ¿Cómo crees que la tecnología está remodelando el panorama económico y laboral?",
    "11. Desde tu perspectiva, ¿cuál es el equilibrio adecuado entre la propiedad privada y la intervención gubernamental en la economía?",
    "12. ¿Cómo la crisis económica global reciente ha cambiado tu percepción sobre la estabilidad financiera?",
    "13. ¿Cuál es tu opinión sobre la renta básica universal como una solución para abordar la pobreza?",
    "14. ¿Crees que la economía debería priorizar el crecimiento económico o la sostenibilidad ambiental?",
    "15. ¿Cuál es tu visión sobre la deuda pública y cómo afecta al desarrollo económico a largo plazo?",
    "16. ¿Cómo pueden las políticas fiscales y monetarias impactar positivamente en el empleo?",
    "17. ¿Qué opinas sobre las criptomonedas y su potencial para transformar el sistema financiero tradicional?",
    "18. ¿Cómo pueden las pequeñas empresas contribuir al desarrollo económico local?",
    "19. ¿Crees que la globalización económica ha beneficiado a todas las naciones por igual?",
    "20. ¿Cuál es tu perspectiva sobre la relación entre la salud económica y el bienestar social?",
    "21. ¿Cuál es tu opinión sobre la participación activa de las empresas en iniciativas sociales y ambientales?",
    "22. Desde tu perspectiva, ¿cómo los cambios en las tasas de interés pueden afectar la toma de decisiones financieras?",
    "23. ¿Qué medidas propondrías para fomentar la igualdad de oportunidades económicas?",
    "24. ¿Cuál es tu visión sobre la responsabilidad social de las empresas en un contexto global?",
    "25. ¿Cómo las políticas económicas pueden abordar los desafíos de la pobreza y la desigualdad?",
    "26. Desde tu experiencia, ¿cómo la innovación tecnológica puede impulsar el crecimiento económico?",
    "27. ¿Qué impacto crees que tiene la globalización en la distribución de la riqueza?",
    "28. ¿Cuál es tu opinión sobre el uso de impuestos para redistribuir la riqueza?",
    "29. ¿Cómo pueden las políticas de comercio internacional afectar a las pequeñas y medianas empresas?",
    "30. Desde tu perspectiva, ¿cómo se pueden abordar los desafíos económicos derivados del cambio climático?",
    "31. ¿Qué medidas propondrías para incentivar la inversión en sectores sostenibles?",
    "32. ¿Cómo la economía colaborativa está cambiando la forma en que entendemos el empleo y los servicios?",
    "33. ¿Qué impacto crees que tiene la deuda estudiantil en la movilidad económica de las personas?",
    "34. ¿Cuál es tu opinión sobre la renta universal frente a la renta básica?",
    "35. ¿Cómo la economía digital está transformando las formas tradicionales de negocios?",
    "36. Desde tu perspectiva, ¿cuál es el papel de las instituciones financieras en el desarrollo económico?",
    "37. ¿Qué medidas propondrías para estimular la innovación en las pequeñas y medianas empresas?",
    "38. ¿Cómo la inteligencia artificial puede afectar la demanda de empleo en diversas industrias?",
    "39. ¿Cuál es tu visión sobre la relación entre el acceso a la educación y el crecimiento económico?",
    "40. ¿Qué impacto crees que tiene la automatización en la distribución del ingreso?",
    "41. ¿Cómo las políticas de comercio internacional pueden abordar la explotación laboral?",
    "42. Desde tu experiencia, ¿cómo la economía circular puede promover la sostenibilidad?",
    "43. ¿Cuál es tu opinión sobre la regulación de las criptomonedas para prevenir actividades ilícitas?",
    "44. ¿Cómo las políticas de incentivos fiscales pueden estimular la inversión extranjera directa?",
    "45. ¿Qué medidas propondrías para mejorar la educación financiera en la población?",
    "46. ¿Cuál es tu visión sobre el papel de los sindicatos en la protección de los derechos laborales?",
    "47. ¿Cómo la economía de la experiencia está afectando a las industrias tradicionales?",
    "48. Desde tu perspectiva, ¿cómo pueden las políticas de vivienda influir en la estabilidad económica?",
    "49. ¿Cuál es tu opinión sobre el uso de aranceles como medida para proteger la industria nacional?",
    "50. ¿Cómo las políticas de inversión en infraestructuras pueden estimular el crecimiento económico?",
    "51. ¿Qué impacto crees que tienen las crisis financieras en la confianza de los consumidores?",
    "52. ¿Cuál es tu visión sobre el desarrollo de monedas digitales emitidas por bancos centrales?",
    "53. ¿Cómo las políticas de inclusión financiera pueden beneficiar a comunidades desfavorecidas?",
    "54. Desde tu experiencia, ¿cómo la movilidad social puede ser promovida a través de políticas económicas?",
    "55. ¿Qué medidas propondrías para abordar la evasión fiscal a nivel internacional?",
    "56. ¿Cómo las políticas de protección del medio ambiente pueden influir en la competitividad económica?",
    "57. ¿Cuál es tu opinión sobre la implementación de impuestos sobre el carbono?",
    "58. ¿Cómo la economía de la atención impacta en los modelos de negocio y la sociedad?",
    "59. Desde tu perspectiva, ¿cómo los acuerdos comerciales pueden afectar a los trabajadores?",
    "60. ¿Qué medidas propondrías para abordar los desafíos económicos derivados de la migración?", 
    ],
    pareja: [
      "1. Más allá de las cualidades superficiales, ¿cuáles son los valores fundamentales que buscas en una pareja?",
      "2. ¿Cómo crees que las diferencias en la gestión de conflictos pueden fortalecer una relación?",
      "3. ¿Cómo defines el éxito en una relación a largo plazo?",
      "4. ¿Cómo crees que la comunicación afecta la salud de una relación?",
      "5. Desde tu perspectiva, ¿cuál es el papel del perdón en una relación duradera?",
      "6. ¿Cómo manejas las expectativas en una relación y qué importancia les das?",
      "7. ¿Cuáles son los desafíos más comunes que enfrentan las parejas en la actualidad?",
      "8. ¿Cuál es tu opinión sobre la independencia versus la interdependencia en una relación?",
      "9. Desde tu experiencia, ¿cómo la confianza se construye y se mantiene en una relación?",
      "10. ¿Qué importancia le das a la igualdad de roles en una relación?",
      "11. ¿Cómo enfrentas los cambios y las transiciones en una relación a largo plazo?",
      "12. ¿Cómo manejas los momentos difíciles y los desacuerdos en una relación?",
      "13. ¿Qué piensas sobre la necesidad de tiempo personal en una relación comprometida?",
      "14. ¿Cuál es tu opinión sobre las relaciones a larga distancia y cómo crees que pueden funcionar?",
      "15. Desde tu experiencia, ¿cómo afecta el estrés externo a la dinámica de pareja?",
      "16. ¿Cuál es tu visión sobre el equilibrio entre la individualidad y la vida en pareja?",
      "17. ¿Cómo manejas las diferencias culturales o de valores en una relación amorosa?",
      "18. ¿Cuáles son tus metas individuales y cómo las integras en una relación de pareja?",
      "19. ¿Cómo influye la empatía en la construcción de una conexión emocional profunda?",
      "20. ¿Cuál es tu enfoque para mantener la intimidad y la conexión emocional en una relación a largo plazo?",
      "21. Desde tu perspectiva, ¿cómo se pueden fortalecer los lazos emocionales en una relación?",
      "22. ¿Qué importancia le das a las actividades compartidas en una relación?",
      "23. ¿Cómo crees que la creatividad puede ser integrada para mantener la chispa en una relación?",
      "24. ¿Cuál es tu opinión sobre la planificación conjunta de metas a largo plazo en una relación?",
      "25. Desde tu experiencia, ¿cómo influye la pasión en la dinámica de una relación amorosa?",
      "26. ¿Cómo manejas los desafíos de la rutina diaria en una relación comprometida?",
      "27. ¿Cuál es tu visión sobre la gestión del tiempo y el espacio individual en una pareja?",
      "28. ¿Qué importancia le das a la espontaneidad y la sorpresa en una relación?",
      "29. ¿Cómo crees que la confianza mutua impacta en la apertura emocional en una relación?",
      "30. Desde tu perspectiva, ¿cómo pueden las parejas mantener una comunicación efectiva durante los tiempos difíciles?",
      "31. ¿Cuál es tu opinión sobre la importancia de la amistad como base de una relación romántica?",
      "32. ¿Cómo manejas las diferencias de opiniones sobre temas importantes en una relación?",
      "33. ¿Qué impacto crees que tienen las expectativas poco realistas en las relaciones amorosas?",
      "34. ¿Cómo influye el apoyo mutuo en el crecimiento individual dentro de una pareja?",
      "35. ¿Cuál es tu visión sobre la importancia de mantener la individualidad en una relación a largo plazo?",
      "36. Desde tu experiencia, ¿cómo se pueden superar los desafíos de la monotonía en una relación?",
      "37. ¿Cómo crees que la paciencia y la tolerancia pueden fortalecer una relación amorosa?",
      "38. ¿Qué medidas propondrías para fomentar la igualdad de responsabilidades en una relación?",
      "39. ¿Cuál es tu opinión sobre la celebración de momentos importantes y aniversarios en una relación?",
      "40. ¿Cómo influyen las metas profesionales individuales en la dinámica de una relación de pareja?",
      "41. ¿Desde tu perspectiva, cómo puede una pareja enfrentar los desafíos financieros juntos?",
      "42. ¿Qué importancia le das a la honestidad y la transparencia en una relación de pareja?",
      "43. ¿Cómo manejas los momentos de cambio y evolución personal dentro de una relación?",
      "44. ¿Cuál es tu visión sobre la resolución constructiva de conflictos en una pareja?",
      "45. Desde tu experiencia, ¿cómo se pueden mantener vivas las llamas de la atracción en una relación a largo plazo?",
      "46. ¿Cómo influyen las experiencias pasadas en la construcción de la confianza en una nueva relación?",
      "47. ¿Cuál es tu opinión sobre la importancia de compartir actividades de ocio en pareja?",
      "48. ¿Cómo manejas las diferencias en los niveles de compromiso en una relación?",
      "49. ¿Qué impacto crees que tiene la independencia financiera en una relación de pareja?",
      "50. ¿Desde tu perspectiva, cómo pueden las parejas fomentar el crecimiento mutuo a lo largo del tiempo?",
      "51. ¿Cuál es tu visión sobre la necesidad de tiempo individual dentro de una relación comprometida?",
      "52. ¿Cómo crees que la exploración de nuevos intereses puede enriquecer una relación?",
      "53. ¿Qué medidas propondrías para mantener una comunicación saludable en una relación de larga distancia?",
      "54. ¿Cuál es tu opinión sobre la importancia de la empatía en situaciones de estrés en una pareja?",
      "55. Desde tu experiencia, ¿cómo pueden las parejas superar la falta de comunicación?",
      "56. ¿Cómo manejas las diferencias culturales o de valores en una relación a largo plazo?",
      "57. ¿Qué importancia le das al equilibrio entre el espacio personal y la conexión emocional?",
      "58. ¿Cuál es tu visión sobre la importancia de la celebración de pequeños logros en una relación?",
      "59. Desde tu perspectiva, ¿cómo influyen las redes sociales en la dinámica de una relación de pareja?",
      "60. ¿Cómo crees que la aceptación mutua puede fortalecer una relación a largo plazo?",
    ],
    ciencia: [
      "1. ¿Cómo crees que la exploración espacial contribuye al avance de la humanidad?",
      "2. Desde tu perspectiva, ¿de qué manera la ciencia puede abordar los desafíos sociales actuales?",
      "3. ¿Cuál es el impacto ético de la investigación científica y tecnológica en la sociedad?",
      "4. ¿Qué importancia le das a la divulgación científica en la educación pública?",
      "5. Desde tu experiencia, ¿cómo la ciencia ha influido en tu comprensión del mundo?",
      "6. ¿Cuál es tu opinión sobre la ingeniería genética y su aplicación en la medicina?",
      "7. ¿Cómo la ciencia puede contribuir a la conservación del medio ambiente?",
      "8. ¿Cuál es tu área científica favorita y por qué te fascina?",
      "9. ¿Cómo la ciencia y la tecnología han transformado la medicina en las últimas décadas?",
      "10. Desde tu perspectiva, ¿cuál es el papel de la ética en la investigación científica?",
      "11. ¿Cómo la ciencia puede abordar los desafíos relacionados con el cambio climático?",
      "12. ¿Cuál es tu opinión sobre la inteligencia artificial y su impacto en la sociedad?",
      "13. ¿Cómo la ciencia ha influido en el desarrollo de la tecnología que usamos a diario?",
      "14. ¿Cuál es tu posición sobre la experimentación animal en la investigación científica?",
      "15. ¿Cómo la ciencia puede contribuir a la comprensión y tratamiento de enfermedades mentales?",
      "16. ¿Cuál es tu opinión sobre la colaboración internacional en proyectos científicos?",
      "17. Desde tu perspectiva, ¿cómo se puede fomentar el interés en la ciencia entre las nuevas generaciones?",
      "18. ¿Cómo crees que la inteligencia artificial puede influir en la evolución humana?",
      "19. ¿Cuál es tu visión sobre la relación entre ciencia y espiritualidad?",
      "20. ¿Cómo la ciencia puede abordar la desinformación y la falta de alfabetización científica?",
      "21. Desde tu perspectiva, ¿cómo la inteligencia artificial puede transformar la investigación científica?",
      "22. ¿Cuál es tu opinión sobre la bioingeniería y su potencial impacto en la salud humana?",
      "23. ¿Cómo la ciencia puede abordar los desafíos éticos relacionados con la edición genética?",
      "24. ¿Qué importancia le das a la investigación espacial en la comprensión del universo?",
      "25. ¿Desde tu experiencia, cómo la ciencia puede influir en la toma de decisiones políticas?",
      "26. ¿Cuál es tu área científica menos comprendida y por qué te resulta intrigante?",
      "27. ¿Cómo la ciencia puede contribuir a la prevención y tratamiento de enfermedades infecciosas?",
      "28. ¿Cuál es tu opinión sobre la relación entre la ciencia y la ética en la inteligencia artificial?",
      "29. ¿Cómo la nanotecnología puede impactar en diversas áreas, desde la medicina hasta la energía?",
      "30. Desde tu perspectiva, ¿cómo la ciencia puede abordar los desafíos de la seguridad alimentaria mundial?",
      "31. ¿Cuál es tu visión sobre la relación entre la ciencia y la creatividad?",
      "32. ¿Cómo la ciencia puede influir en la gestión sostenible de los recursos naturales?",
      "33. ¿Cuál es tu opinión sobre la aplicación de la realidad virtual en la investigación científica?",
      "34. ¿Cómo la ciencia puede abordar los problemas de salud mental en la sociedad moderna?",
      "35. ¿Desde tu experiencia, cómo la ciencia puede contribuir a la conservación de la biodiversidad?",
      "36. ¿Cuál es tu visión sobre la relación entre la ciencia y la filosofía?",
      "37. ¿Cómo la investigación científica puede abordar los desafíos éticos de la inteligencia artificial?",
      "38. ¿Qué importancia le das a la ciencia ciudadana en la recopilación de datos científicos?",
      "39. ¿Cuál es tu opinión sobre la ingeniería ambiental y su papel en la sostenibilidad?",
      "40. ¿Cómo la ciencia puede abordar los desafíos de la seguridad cibernética en la era digital?",
      "41. Desde tu perspectiva, ¿cómo la ciencia puede contribuir a la exploración y colonización espacial?",
      "42. ¿Cuál es tu visión sobre la relación entre la ciencia y la economía?",
      "43. ¿Cómo la ciencia puede abordar los desafíos de la inteligencia artificial en la medicina?",
      "44. ¿Qué importancia le das a la ética en la investigación científica sobre la inteligencia artificial?",
      "45. ¿Desde tu experiencia, cómo la ciencia puede abordar la resistencia a los antibióticos?",
      "46. ¿Cuál es tu opinión sobre la investigación científica en el campo de la psicología y la mente humana?",
      "47. ¿Cómo la ciencia puede contribuir a la gestión sostenible de los ecosistemas marinos?",
      "48. ¿Qué impacto crees que tiene la ciencia en la toma de decisiones éticas a nivel global?",
      "49. ¿Desde tu perspectiva, cómo la ciencia puede abordar los desafíos de la inteligencia artificial en la educación?",
      "50. ¿Cuál es tu visión sobre la relación entre la ciencia y la ética en la investigación espacial?",
      "51. ¿Cómo la investigación científica puede abordar los desafíos éticos en la clonación?",
      "52. ¿Qué importancia le das a la investigación científica en la prevención de pandemias?",
      "53. ¿Cuál es tu opinión sobre la ingeniería biomédica y su impacto en la salud humana?",
      "54. ¿Desde tu experiencia, cómo la ciencia puede influir en la gestión de desastres naturales?",
      "55. ¿Cómo la investigación científica puede abordar los desafíos éticos de la inteligencia artificial en el campo legal?",
      "56. ¿Cuál es tu visión sobre la relación entre la ciencia y la ética en la investigación genética?",
      "57. ¿Qué importancia le das a la investigación científica en la prevención del cambio climático?",
      "58. ¿Cómo la ciencia puede contribuir a la producción sostenible de alimentos a nivel global?",
      "59. Desde tu perspectiva, ¿cómo la ciencia puede abordar los desafíos éticos en la medicina regenerativa?",
      "60. ¿Cuál es tu opinión sobre la relación entre la ciencia y la ética en la inteligencia artificial aplicada a la seguridad?",
        ],
    psicologia: [
      "1. ¿Cómo integras la gestión del estrés en tu vida cotidiana para fomentar la salud mental?",
      "2. ¿Cuál es tu enfoque filosófico para mantener un equilibrio emocional en situaciones desafiantes?",
      "3. ¿Cómo podemos promover una mayor conciencia y comprensión de la salud mental en la sociedad?",
      "4. Desde tu perspectiva, ¿cómo influyen las experiencias de la infancia en la salud mental en la edad adulta?",
      "5. ¿Cuál es tu opinión sobre la terapia psicológica y su impacto en el bienestar emocional?",
      "6. ¿Cómo abordas la autoevaluación y el crecimiento personal en tu vida diaria?",
      "7. ¿Cuál es tu visión sobre la relación entre la espiritualidad y la salud mental?",
      "8. ¿Cómo la práctica de la atención plena puede contribuir al bienestar psicológico?",
      "9. ¿Cuáles son tus estrategias para fomentar la resiliencia emocional en situaciones difíciles?",
      "10. Desde tu perspectiva, ¿cómo se pueden reducir el estigma y los prejuicios en torno a las enfermedades mentales?",
      "11. ¿Cómo influyen las relaciones interpersonales en la salud mental y el bienestar emocional?",
      "12. ¿Cuál es tu opinión sobre el impacto de la tecnología en la salud mental de las personas?",
      "13. ¿Cómo la expresión creativa puede ser una herramienta para la gestión emocional?",
      "14. ¿Qué importancia le das a la autorreflexión en el mantenimiento de la salud mental?",
      "15. ¿Cómo abordas los desafíos emocionales en tus relaciones personales y profesionales?",
      "16. Desde tu experiencia, ¿cómo se puede mejorar el acceso a servicios de salud mental a nivel comunitario?",
      "17. ¿Cuál es tu perspectiva sobre el equilibrio entre el trabajo y la salud mental en la sociedad actual?",
      "18. ¿Cómo crees que la educación en salud mental puede impactar positivamente en las comunidades?",
      "19. Desde tu perspectiva, ¿cómo se pueden fomentar entornos laborales saludables desde el punto de vista psicológico?",
      "20. ¿Cuál es tu opinión sobre la relación entre la creatividad y la salud mental?",
      "21. ¿Cómo la psicología positiva puede contribuir al bienestar individual y colectivo?",
      "22. ¿Cuál es tu opinión sobre la relación entre la nutrición y la salud mental?",
      "23. ¿Cómo la psicología evolutiva puede arrojar luz sobre los patrones de comportamiento humano?",
      "24. Desde tu perspectiva, ¿cómo afectan las redes sociales a la salud mental de las personas?",
      "25. ¿Cuál es tu enfoque para cultivar relaciones interpersonales saludables en tu vida?",
      "26. ¿Cómo la terapia cognitivo-conductual puede ser aplicada en situaciones cotidianas?",
      "27. ¿Cuál es tu visión sobre la conexión entre la psicología y la toma de decisiones?",
      "28. ¿Cómo la psicología infantil puede informar sobre la crianza y la educación?",
      "29. ¿Cuáles son tus estrategias para mantener la salud mental durante períodos de cambio?",
      "30. Desde tu perspectiva, ¿cómo influye la psicología en la formación de hábitos?",
      "31. ¿Cuál es tu opinión sobre la relación entre la psicología y la inteligencia emocional?",
      "32. ¿Cómo la psicología puede abordar los desafíos específicos de la salud mental en la adolescencia?",
      "33. ¿Qué importancia le das a la psicología en la comprensión de los trastornos del sueño?",
      "34. ¿Cómo la psicología comunitaria puede contribuir al bienestar de áreas específicas?",
      "35. ¿Desde tu experiencia, cómo la meditación puede influir en la salud mental?",
      "36. ¿Cuál es tu perspectiva sobre la conexión entre la psicología y la creatividad en el trabajo?",
      "37. ¿Cómo la psicología forense puede contribuir a la administración de la justicia?",
      "38. ¿Qué impacto crees que tiene la publicidad en la salud mental de las personas?",
      "39. Desde tu perspectiva, ¿cómo la psicología puede abordar los desafíos del envejecimiento?",
      "40. ¿Cuál es tu opinión sobre la relación entre la psicología y la toma de decisiones éticas?",
      "41. ¿Cómo la psicología de la personalidad puede influir en las dinámicas de grupo?",
      "42. ¿Qué importancia le das a la psicología en la gestión del estrés postraumático?",
      "43. ¿Desde tu experiencia, cómo la psicología puede ser aplicada en situaciones de crisis?",
      "44. ¿Cuál es tu visión sobre la relación entre la psicología y la inteligencia artificial?",
      "45. ¿Cómo la psicología organizacional puede contribuir a entornos de trabajo saludables?",
      "46. ¿Qué impacto crees que tiene la psicología en la comprensión de los trastornos alimentarios?",
      "47. Desde tu perspectiva, ¿cómo la psicología puede abordar los desafíos de la adicción?",
      "48. ¿Cuál es tu opinión sobre la relación entre la psicología y la tecnología de la información?",
      "49. ¿Cómo la psicología transcultural puede enriquecer la comprensión de las diferencias culturales?",
      "50. ¿Desde tu experiencia, cómo la psicología puede influir en la gestión del dolor crónico?",
      "51. ¿Cuál es tu visión sobre la conexión entre la psicología y la resiliencia?",
      "52. ¿Cómo la psicología educativa puede mejorar los métodos de enseñanza y aprendizaje?",
      "53. ¿Qué importancia le das a la psicología en la prevención del agotamiento laboral?",
      "54. ¿Desde tu perspectiva, cómo la psicología puede abordar los desafíos de la soledad?",
      "55. ¿Cuál es tu opinión sobre la relación entre la psicología y la economía del comportamiento?",
      "56. ¿Cómo la psicología ambiental puede influir en el diseño de espacios urbanos?",
      "57. ¿Qué impacto crees que tiene la psicología en la comprensión de la memoria y el olvido?",
      "58. Desde tu experiencia, ¿cómo la psicología puede ser aplicada en el ámbito deportivo?",
      "59. ¿Cuál es tu visión sobre la conexión entre la psicología y la inteligencia colectiva?",
      "60. ¿Cómo la psicología puede abordar los desafíos específicos de la salud mental en la tercera edad?",
      "61. ¿Qué importancia le das a la psicología en la gestión del estrés laboral?",
    ],
    religion: [
      "1. ¿Cómo influye tu religión en tus decisiones y acciones diarias?",
      "2. ¿Cuál es tu perspectiva sobre la espiritualidad en un mundo cada vez más secularizado?",
      "3. ¿Cómo abordas las diferencias religiosas al construir relaciones significativas?",
      "4. Desde tu punto de vista, ¿cuál es la relación entre la moralidad y la religión?",
      "5. ¿Cómo la práctica religiosa puede afectar la percepción del propósito y significado en la vida?",
      "6. ¿Cuál es tu opinión sobre la coexistencia pacífica entre personas con diferentes creencias religiosas?",
      "7. ¿Cómo manejas las dudas o cuestionamientos dentro de tu propia fe?",
      "8. Desde tu perspectiva, ¿cómo la religión puede contribuir a la construcción de comunidades solidarias?",
      "9. ¿Qué importancia le das a la oración o meditación en tu práctica religiosa?",
      "10. ¿Cómo la religión puede proporcionar consuelo y apoyo durante momentos de crisis personal?",
      "11. ¿Cuál es tu opinión sobre la relación entre la ciencia y la religión?",
      "12. ¿Cómo la religión puede influir en las decisiones éticas y morales en la vida cotidiana?",
      "13. ¿Cómo las festividades religiosas contribuyen a la cohesión social en tu comunidad?",
      "14. ¿Cuál es tu perspectiva sobre el papel de las mujeres en las instituciones religiosas?",
      "15. Desde tu experiencia, ¿cómo la religión ha influido en tu sentido de identidad y pertenencia?",
      "16. ¿Cómo abordas la diversidad de interpretaciones dentro de tu propia tradición religiosa?",
      "17. ¿Cuál es tu visión sobre el papel de las religiones en la promoción de la paz mundial?",
      "18. ¿Cómo crees que la espiritualidad puede contribuir al bienestar emocional y mental?",
      "19. ¿Cuál es tu perspectiva sobre la relación entre la religión y la justicia social?",
      "20. Desde tu punto de vista, ¿cómo la religión puede abordar los desafíos éticos de la sociedad contemporánea?",
      "21. ¿Cómo crees que la religión puede facilitar el diálogo interreligioso y la comprensión mutua?",
      "22. ¿Cuál es tu opinión sobre el papel de la religión en la formación de normas sociales?",
      "23. ¿Cómo manejas los desafíos éticos dentro de tu comunidad religiosa?",
      "24. Desde tu perspectiva, ¿cómo la religión puede contribuir a la preservación del medio ambiente?",
      "25. ¿Cuál es tu visión sobre el papel de la música y el arte en la expresión religiosa?",
      "26. ¿Cómo la religión puede abordar los problemas de desigualdad y discriminación en la sociedad?",
      "27. ¿Cuál es tu opinión sobre la relación entre la espiritualidad y la salud física?",
      "28. ¿Cómo manejas las diferencias generacionales en la interpretación de enseñanzas religiosas?",
      "29. ¿Qué importancia le das a la educación religiosa en la formación de valores?",
      "30. Desde tu perspectiva, ¿cómo la religión puede influir en la toma de decisiones políticas?",
      "31. ¿Cuál es tu visión sobre el papel de la caridad y la obra social en tu tradición religiosa?",
      "32. ¿Cómo la religión puede abordar los desafíos éticos de la tecnología moderna?",
      "33. ¿Qué impacto crees que tiene la religión en la percepción de la vida después de la muerte?",
      "34. ¿Cuál es tu opinión sobre la relación entre la religión y la ética empresarial?",
      "35. ¿Cómo manejas las contradicciones o interpretaciones conflictivas dentro de tu fe?",
      "36. Desde tu experiencia, ¿cómo la religión puede ser un puente entre diferentes culturas?",
      "37. ¿Cuál es tu perspectiva sobre el papel de las prácticas rituales en la religión?",
      "38. ¿Cómo la religión puede abordar los desafíos éticos de la ingeniería genética?",
      "39. ¿Qué importancia le das al diálogo interreligioso en el panorama global actual?",
      "40. ¿Desde tu perspectiva, cómo la religión puede contribuir a la prevención de conflictos?",
      "41. ¿Cuál es tu opinión sobre la relación entre la religión y la equidad de género?",
      "42. ¿Cómo manejas las tensiones entre la libertad religiosa y los derechos humanos universales?",
      "43. Desde tu experiencia, ¿cómo la religión puede influir en las decisiones sobre la bioética?",
      "44. ¿Cuál es tu visión sobre el papel de la fe en tiempos de avance tecnológico rápido?",
      "45. ¿Cómo la religión puede abordar los desafíos éticos de la inteligencia artificial?",
      "46. ¿Qué impacto crees que tiene la religión en la formación de políticas de inmigración?",
      "47. ¿Cuál es tu opinión sobre la relación entre la religión y la diversidad sexual?",
      "48. ¿Cómo manejas las interpretaciones fundamentalistas o extremistas dentro de tu religión?",
      "49. Desde tu perspectiva, ¿cómo la religión puede contribuir a la justicia económica?",
      "50. ¿Cuál es tu visión sobre el papel de las peregrinaciones en la práctica religiosa?",
      "51. ¿Cómo la religión puede abordar los desafíos éticos de la ingeniería climática?",
      "52. ¿Qué importancia le das a la interpretación personal de las escrituras en tu fe?",
      "53. Desde tu experiencia, ¿cómo la religión puede influir en la percepción de la moralidad?",
      "54. ¿Cuál es tu opinión sobre la relación entre la religión y la conservación del patrimonio cultural?",
      "55. ¿Cómo manejas las tensiones entre la libertad de expresión y la sensibilidad religiosa?",
      "56. ¿Desde tu perspectiva, cómo la religión puede contribuir a la reconciliación en conflictos?",
      "57. ¿Cuál es tu visión sobre el papel de la religión en la atención médica y la toma de decisiones médicas éticas?",
      "58. ¿Cómo la religión puede abordar los desafíos éticos de la inteligencia artificial en la atención médica?",
      "59. ¿Qué impacto crees que tiene la religión en la participación ciudadana y la responsabilidad social?",
      "60. ¿Desde tu experiencia, cómo la religión puede ser una fuerza para el cambio social positivo?",
        ],
    politica: [
      "1. ¿Cómo crees que la política puede ser una herramienta efectiva para el cambio positivo?",
      "2. Desde tu perspectiva, ¿cuáles son los mayores desafíos políticos que enfrenta tu país?",
      "3. ¿Qué papel juegan los ciudadanos comunes en la formación y mejora de sistemas políticos?",
      "4. ¿Cuál es tu opinión sobre la participación de la juventud en la política y la toma de decisiones?",
      "5. Desde tu experiencia, ¿cómo se pueden abordar las divisiones políticas y fomentar la unidad?",
      "6. ¿Cuál es tu perspectiva sobre la ética en la toma de decisiones políticas?",
      "7. ¿Cómo la política local puede impactar directamente en la calidad de vida de las comunidades?",
      "8. Desde tu punto de vista, ¿cuál es el papel de la tecnología en la participación política?",
      "9. ¿Cómo influyen las ideologías políticas en la formación de tus valores personales?",
      "10. ¿Cuál es tu visión sobre la relación entre la política y la justicia social?",
      "11. ¿Cómo la política puede abordar los problemas medioambientales a nivel global?",
      "12. ¿Cuál es tu opinión sobre el sistema electoral de tu país?",
      "13. Desde tu perspectiva, ¿cómo se pueden equilibrar los intereses individuales y colectivos en la política?",
      "14. ¿Cómo afectan las decisiones políticas en la distribución de recursos y oportunidades?",
      "15. ¿Cuál es tu enfoque para mantener un diálogo respetuoso sobre temas políticos con personas de opiniones diferentes?",
      "16. ¿Qué importancia le das a la transparencia y la rendición de cuentas en la política?",
      "17. Desde tu experiencia, ¿cómo se pueden abordar los desafíos de la corrupción en la política?",
      "18. ¿Cuál es tu perspectiva sobre la participación de las minorías en la política?",
      "19. ¿Cómo la política puede influir en la educación y el acceso a oportunidades para todos?",
      "20. ¿Qué cambios propondrías para mejorar la participación ciudadana en la toma de decisiones políticas?",
      "21. ¿Cómo crees que la tecnología puede transformar la participación política y el activismo?",
      "22. ¿Cuál es tu opinión sobre la relación entre la política y la equidad de género?",
      "23. ¿Cómo influye la globalización en la dinámica política de tu región?",
      "24. Desde tu perspectiva, ¿cómo la política puede abordar los desafíos de la migración?",
      "25. ¿Cuál es tu visión sobre el papel de los medios de comunicación en la formación de opiniones políticas?",
      "26. ¿Cómo la política puede abordar los problemas de desigualdad económica en tu sociedad?",
      "27. ¿Cuál es tu enfoque para fomentar la participación política entre los jóvenes?",
      "28. Desde tu punto de vista, ¿cómo influyen las redes sociales en el panorama político?",
      "29. ¿Qué importancia le das al diálogo bipartidista en la toma de decisiones políticas?",
      "30. ¿Cómo la política puede abordar los desafíos éticos de la inteligencia artificial en la gobernanza?",
      "31. ¿Cuál es tu opinión sobre la relación entre la política y los derechos humanos?",
      "32. ¿Cómo afectan las políticas gubernamentales a la inclusión social de las personas con discapacidades?",
      "33. Desde tu perspectiva, ¿cómo la política puede contribuir a la lucha contra la discriminación racial?",
      "34. ¿Cuál es tu visión sobre el papel de las organizaciones no gubernamentales (ONG) en la política?",
      "35. ¿Cómo la política puede abordar los desafíos éticos de la biotecnología y la ingeniería genética?",
      "36. ¿Qué impacto crees que tiene la política en la percepción de la justicia en la sociedad?",
      "37. Desde tu experiencia, ¿cómo la política puede abordar los desafíos del acceso a la vivienda?",
      "38. ¿Cuál es tu perspectiva sobre la participación política de las comunidades indígenas?",
      "39. ¿Cómo influye la política en la gestión de crisis, como pandemias o desastres naturales?",
      "40. ¿Desde tu perspectiva, cómo la política puede abordar los desafíos de la ciberseguridad?",
      "41. ¿Cuál es tu opinión sobre la relación entre la política y la gestión de recursos naturales?",
      "42. ¿Cómo la política puede influir en la aprobación y aplicación de leyes de derechos civiles?",
      "43. ¿Qué importancia le das a la educación cívica en la formación de ciudadanos políticamente activos?",
      "44. Desde tu perspectiva, ¿cómo la política puede abordar los desafíos de la inteligencia artificial en la seguridad nacional?",
      "45. ¿Cuál es tu visión sobre el papel de la política en la promoción de la igualdad de oportunidades?",
      "46. ¿Cómo afectan las políticas de inmigración en la diversidad cultural de una sociedad?",
      "47. ¿Desde tu experiencia, cómo la política puede abordar los desafíos de la desinformación?",
      "48. ¿Cuál es tu opinión sobre la relación entre la política y la protección del medio ambiente?",
      "49. ¿Cómo la política puede abordar los problemas de acceso y asequibilidad a la atención médica?",
      "50. ¿Desde tu perspectiva, cómo la política puede contribuir a la resolución de conflictos internacionales?",
      "51. ¿Cuál es tu visión sobre el papel de la política en la regulación de la tecnología financiera?",
      "52. ¿Cómo la política puede abordar los desafíos éticos de la inteligencia artificial en la economía?",
      "53. ¿Qué impacto crees que tiene la política en la movilidad social de las personas?",
      "54. Desde tu experiencia, ¿cómo la política puede abordar los desafíos de la inteligencia artificial en la privacidad?",
      "55. ¿Cuál es tu perspectiva sobre la relación entre la política y la gestión de la crisis climática?",
      "56. ¿Cómo influye la política en la promoción de la diversidad y la inclusión en el ámbito laboral?",
      "57. Desde tu perspectiva, ¿cómo la política puede abordar los desafíos de la inteligencia artificial en la educación?",
      "58. ¿Cuál es tu opinión sobre la relación entre la política y la regulación de las redes sociales?",
      "59. ¿Cómo la política puede influir en la adopción de políticas de energía sostenible?",
      "60. ¿Desde tu experiencia, cómo la política puede abordar los desafíos de la inteligencia artificial en la ética empresarial?",
        ],
    desarrollo: [
      "1. ¿Cómo defines y persigues el desarrollo personal significativo?",
      "2. ¿Cuáles son los principales obstáculos que enfrentas al trabajar hacia tus metas a largo plazo?",
      "3. Desde tu experiencia, ¿cuál es la conexión entre la autenticidad y el crecimiento personal?",
      "4. ¿Cuál es tu enfoque para superar los momentos de estancamiento en tu desarrollo personal?",
      "5. ¿Cómo la autoevaluación constante contribuye a tu proceso de desarrollo?",
      "6. Desde tu perspectiva, ¿cómo influye la educación continua en el desarrollo personal?",
      "7. ¿Qué importancia le das a la adaptabilidad y la flexibilidad en tu búsqueda de desarrollo?",
      "8. ¿Cómo la construcción de relaciones significativas impacta en tu crecimiento personal?",
      "9. ¿Cuáles son tus estrategias para mantener un equilibrio entre el desarrollo profesional y personal?",
      "10. Desde tu punto de vista, ¿cómo la resiliencia juega un papel crucial en el desarrollo?",
      "11. ¿Cuál es tu visión sobre el concepto de éxito en el contexto del desarrollo personal?",
      "12. ¿Cómo influyen las experiencias de fracaso en tu enfoque hacia el desarrollo?",
      "13. ¿Cuál es tu perspectiva sobre la importancia del desarrollo emocional en la vida cotidiana?",
      "14. Desde tu experiencia, ¿cómo se pueden superar los miedos y las dudas en el camino del desarrollo?",
      "15. ¿Qué aprendizajes significativos has obtenido de tus mayores desafíos en el desarrollo personal?",
      "16. ¿Cómo la automotivación y la disciplina contribuyen al progreso en el desarrollo personal?",
      "17. ¿Cuál es tu opinión sobre la relación entre el desarrollo personal y la contribución a la sociedad?",
      "18. ¿Cómo la creatividad y la innovación pueden impulsar el desarrollo personal?",
      "19. ¿Cuáles son tus metas a largo plazo en tu viaje de desarrollo personal?",
      "20. ¿Qué consejos darías a alguien que busca iniciar su propio camino de desarrollo personal?",
      "21. ¿Cómo cultivas la gratitud en tu vida y cómo contribuye al desarrollo personal?",
      "22. ¿Cuál es tu perspectiva sobre la importancia de la autoaceptación en el camino del desarrollo personal?",
      "23. Desde tu experiencia, ¿cómo se pueden convertir los fracasos en oportunidades de crecimiento?",
      "24. ¿Qué papel juegan los hábitos saludables en tu búsqueda de desarrollo personal?",
      "25. ¿Cuál es tu enfoque para manejar la presión y el estrés mientras buscas el desarrollo personal?",
      "26. ¿Cómo influye la mentalidad de crecimiento en tu actitud hacia el desarrollo personal?",
      "27. ¿Qué importancia le das a la gestión del tiempo en tu proceso de desarrollo?",
      "28. Desde tu perspectiva, ¿cómo la práctica de la meditación puede contribuir al desarrollo personal?",
      "29. ¿Cuáles son las lecciones más valiosas que has aprendido de tus mentores en tu viaje de desarrollo personal?",
      "30. ¿Cómo la exposición a diferentes perspectivas y culturas impacta en tu desarrollo personal?",
      "31. ¿Cuál es tu opinión sobre la relación entre el bienestar físico y el desarrollo personal?",
      "32. ¿Cómo influye la planificación a largo plazo en tu proceso de desarrollo personal?",
      "33. Desde tu experiencia, ¿cómo la celebración de logros pequeños impulsa el desarrollo personal?",
      "34. ¿Cuál es tu perspectiva sobre el papel de la espiritualidad en el desarrollo personal?",
      "35. ¿Cómo la autenticidad y la coherencia contribuyen a la integridad en el desarrollo personal?",
      "36. ¿Qué impacto crees que tienen las experiencias de viaje en el crecimiento personal?",
      "37. Desde tu perspectiva, ¿cómo la construcción de redes de apoyo influye en el desarrollo personal?",
      "38. ¿Cuál es tu visión sobre el equilibrio entre la autoexigencia y la autocompasión en el desarrollo personal?",
      "39. ¿Cómo influye la lectura y la adquisición de conocimientos en tu desarrollo personal?",
      "40. ¿Desde tu experiencia, cómo la asunción de responsabilidades impulsa el desarrollo personal?",
      "41. ¿Cuál es tu opinión sobre la relación entre el desarrollo personal y el liderazgo?",
      "42. ¿Cómo la exposición a nuevas experiencias y desafíos contribuye a tu desarrollo personal?",
      "43. Desde tu perspectiva, ¿cómo se puede encontrar un propósito significativo en la vida?",
      "44. ¿Qué importancia le das a la autorreflexión en tu viaje de desarrollo personal?",
      "45. ¿Cómo influye la práctica del mindfulness en el desarrollo de la inteligencia emocional?",
      "46. ¿Cuál es tu visión sobre el papel de la educación formal en el desarrollo personal?",
      "47. ¿Cómo la construcción de habilidades de comunicación impacta en el desarrollo personal?",
      "48. Desde tu experiencia, ¿cómo el establecimiento de límites contribuye al desarrollo personal?",
      "49. ¿Cuál es tu perspectiva sobre la relación entre la gestión financiera y el desarrollo personal?",
      "50. ¿Cómo influye la resolución de conflictos en el crecimiento personal y las relaciones?",
      "51. ¿Qué aprendizajes has obtenido de los momentos de soledad en tu viaje de desarrollo personal?",
      "52. Desde tu perspectiva, ¿cómo la toma de riesgos calculados impulsa el desarrollo personal?",
      "53. ¿Cuál es tu opinión sobre la relación entre la creatividad y la expresión personal en el desarrollo?",
      "54. ¿Cómo la conexión con la naturaleza contribuye a tu bienestar y desarrollo personal?",
      "55. ¿Desde tu experiencia, cómo la práctica de la empatía influye en el desarrollo de relaciones?",
      "56. ¿Cuál es tu visión sobre el equilibrio entre la autosuficiencia y la colaboración en el desarrollo personal?",
      "57. ¿Cómo influye la gestión efectiva de metas en tu proceso de desarrollo personal?",
      "58. Desde tu perspectiva, ¿cómo el aprendizaje continuo y la adquisición de nuevas habilidades contribuyen al desarrollo personal?",
      "59. ¿Cuál es tu opinión sobre la relación entre el desarrollo personal y la creatividad artística?",
      "60. ¿Cómo la práctica de la empatía y la compasión hacia uno mismo impacta en el desarrollo personal?",
    ],
    filosofia: [
      "1. ¿Cuál es tu filosofía fundamental sobre la vida y el significado personal?",
      "2. Desde tu perspectiva, ¿cómo puede uno alcanzar una verdadera felicidad y satisfacción?",
      "3. ¿Cómo influye tu visión filosófica en tus decisiones y acciones diarias?",
      "4. ¿Cuál es tu opinión sobre la conexión entre la filosofía y la ética?",
      "5. Desde tu punto de vista, ¿cuál es el papel de la espiritualidad en tu filosofía de vida?",
      "6. ¿Cómo abordas las contradicciones y los dilemas éticos desde tu perspectiva filosófica?",
      "7. ¿Cuál es tu visión sobre la relación entre la libertad individual y la responsabilidad colectiva?",
      "8. Desde tu experiencia, ¿cómo la filosofía puede proporcionar guía en situaciones difíciles?",
      "9. ¿Qué importancia le das a la autenticidad y la coherencia en tu filosofía de vida?",
      "10. ¿Cómo la reflexión filosófica puede enriquecer las relaciones interpersonales?",
      "11. ¿Cuál es tu posición sobre la relación entre la razón y la intuición en la toma de decisiones?",
      "12. Desde tu perspectiva filosófica, ¿cómo defines el concepto de justicia?",
      "13. ¿Cuál es tu enfoque para reconciliar las diferencias filosóficas en discusiones y debates?",
      "14. ¿Cómo la filosofía puede ayudar a las personas a encontrar sentido en situaciones de adversidad?",
      "15. ¿Cuál es tu opinión sobre la relación entre la filosofía y la creatividad?",
      "16. Desde tu experiencia, ¿cómo la filosofía ha influido en tus valores morales?",
      "17. ¿Cómo abordas la búsqueda de significado y propósito en la existencia desde una perspectiva filosófica?",
      "18. ¿Cuál es tu posición sobre la relación entre la filosofía y la ciencia?",
      "19. ¿Cómo la filosofía puede contribuir al bienestar emocional y mental de las personas?",
      "20. ¿Qué consejos darías a alguien interesado en explorar y desarrollar su propia filosofía de vida?",
      "21. ¿Cómo integras la filosofía de la simplicidad en tu vida diaria?",
      "22. ¿Cuál es tu perspectiva sobre la relación entre la filosofía y la resiliencia emocional?",
      "23. Desde tu experiencia, ¿cómo la filosofía puede contribuir a la toma de decisiones éticas?",
      "24. ¿Cuál es tu enfoque para cultivar la gratitud como parte de tu filosofía de vida?",
      "25. ¿Cómo la filosofía puede ayudar a las personas a encontrar equilibrio en una sociedad acelerada?",
      "26. ¿Cuál es tu posición sobre la conexión entre la filosofía y la gestión del tiempo?",
      "27. Desde tu perspectiva, ¿cómo la filosofía puede abordar los desafíos de la vida moderna?",
      "28. ¿Qué importancia le das a la atención plena en tu práctica filosófica?",
      "29. ¿Cuáles son los principios fundamentales que guían tu filosofía de relaciones interpersonales?",
      "30. ¿Cómo la filosofía puede contribuir a la construcción de comunidades más compasivas?",
      "31. ¿Cuál es tu opinión sobre la relación entre la filosofía y el desarrollo personal?",
      "32. Desde tu experiencia, ¿cómo la filosofía puede abordar los desafíos de la sociedad contemporánea?",
      "33. ¿Cómo abordas las contradicciones entre tus valores personales y tu filosofía de vida?",
      "34. ¿Cuál es tu visión sobre el equilibrio entre la introspección y la acción en la filosofía de vida?",
      "35. ¿Cómo la filosofía puede ayudar a las personas a encontrar significado en un mundo complejo?",
      "36. ¿Desde tu perspectiva, cómo la filosofía puede contribuir a la resolución de conflictos?",
      "37. ¿Cuál es tu posición sobre la conexión entre la filosofía y la ecología?",
      "38. Desde tu experiencia, ¿cómo la filosofía puede abordar los desafíos de la era digital?",
      "39. ¿Cómo la filosofía puede inspirar la creatividad y la innovación en la vida cotidiana?",
      "40. ¿Cuál es tu enfoque para cultivar la empatía como parte de tu filosofía de vida?",
      "41. ¿Qué importancia le das a la comunidad y la colaboración en tu filosofía de vida?",
      "42. ¿Cómo la filosofía puede contribuir a la construcción de un sentido de pertenencia?",
      "43. ¿Cuál es tu perspectiva sobre la relación entre la filosofía y la educación?",
      "44. Desde tu experiencia, ¿cómo la filosofía ha influido en tu perspectiva del tiempo?",
      "45. ¿Cómo abordas la incertidumbre desde una perspectiva filosófica en tu vida?",
      "46. ¿Cuál es tu visión sobre el equilibrio entre la planificación y la espontaneidad en la filosofía de vida?",
      "47. Desde tu perspectiva, ¿cómo la filosofía puede abordar los desafíos éticos de la inteligencia artificial?",
      "48. ¿Qué impacto crees que tiene la filosofía en la construcción de sociedades más justas?",
      "49. ¿Cuál es tu opinión sobre la relación entre la filosofía y la igualdad de género?",
      "50. ¿Cómo la filosofía puede abordar los problemas de desigualdad social en la sociedad?",
      "51. ¿Desde tu experiencia, cómo la filosofía puede contribuir a la construcción de la paz?",
      "52. ¿Cuál es tu perspectiva sobre el equilibrio entre la individualidad y la conexión social en la filosofía de vida?",
      "53. ¿Cómo la filosofía puede ayudar a las personas a enfrentar los desafíos de la mortalidad?",
      "54. Desde tu perspectiva, ¿cómo la filosofía puede abordar los problemas de salud mental?",
      "55. ¿Cuál es tu enfoque para cultivar la resiliencia emocional como parte de tu filosofía de vida?",
      "56. ¿Cómo la filosofía puede contribuir a la construcción de una sociedad más inclusiva?",
      "57. ¿Qué importancia le das a la autenticidad y la autoexpresión en tu filosofía de vida?",
      "58. Desde tu experiencia, ¿cómo la filosofía puede abordar los desafíos de la convivencia multicultural?",
      "59. ¿Cuál es tu opinión sobre la relación entre la filosofía y la tecnología?",
      "60. ¿Cómo abordas las decisiones éticas en tu vida cotidiana desde una perspectiva filosófica?",
        ],
    tecnologia: [
      "1. ¿Cómo crees que la tecnología puede ser utilizada de manera ética para mejorar la calidad de vida?",
      "2. Desde tu experiencia, ¿cuáles son los beneficios y desafíos de depender de la tecnología en la vida diaria?",
      "3. ¿Cómo podemos equilibrar el avance tecnológico con la preservación de valores humanos fundamentales?",
      "4. ¿Cuál es tu opinión sobre la influencia de la inteligencia artificial en la toma de decisiones éticas?",
      "5. Desde tu perspectiva, ¿cómo la tecnología puede impactar positivamente la educación?",
      "6. ¿Cuál es tu visión sobre la privacidad en la era digital y cómo debería abordarse?",
      "7. ¿Cómo crees que la tecnología puede contribuir a resolver desafíos globales como el cambio climático?",
      "8. Desde tu experiencia, ¿cuál es el papel de la tecnología en la conectividad y las relaciones interpersonales?",
      "9. ¿Qué medidas éticas propondrías para el desarrollo y uso de la realidad virtual?",
      "10. ¿Cuál es tu perspectiva sobre la influencia de las redes sociales en la sociedad actual?",
      "11. ¿Cómo la tecnología ha afectado la forma en que consumes y compartes información?",
      "12. Desde tu punto de vista, ¿cómo puede la tecnología ser una herramienta para la inclusión social?",
      "13. ¿Cuál es tu opinión sobre la ética de la ingeniería genética y la modificación del ADN humano?",
      "14. ¿Cómo la tecnología puede desempeñar un papel en la resolución de problemas de salud a nivel mundial?",
      "15. Desde tu experiencia, ¿cómo la tecnología ha influido en la creatividad y la expresión artística?",
      "16. ¿Cuál es tu posición sobre el equilibrio entre la seguridad nacional y la privacidad individual en la era digital?",
      "17. ¿Cómo crees que la inteligencia artificial podría transformar el ámbito laboral en el futuro?",
      "18. ¿Cuál es tu visión sobre la sostenibilidad en el desarrollo y producción de tecnología?",
      "19. Desde tu perspectiva, ¿cómo la tecnología puede influir en la toma de decisiones políticas?",
      "20. ¿Qué medidas sugerirías para abordar la brecha digital y garantizar el acceso equitativo a la tecnología?",
      "21. ¿Cómo la tecnología puede mejorar la accesibilidad para personas con discapacidades?",
      "22. ¿Cuál es tu perspectiva sobre la ética de la inteligencia artificial en la toma de decisiones médicas?",
      "23. Desde tu experiencia, ¿cómo la tecnología puede influir en la igualdad de oportunidades en la educación?",
      "24. ¿Cuál es tu opinión sobre el papel de la tecnología en la transformación de las ciudades hacia 'ciudades inteligentes'?",
      "25. ¿Cómo la realidad aumentada podría cambiar la forma en que interactuamos con el mundo?",
      "26. ¿Cuál es tu visión sobre la ética de la edición genética en humanos?",
      "27. Desde tu perspectiva, ¿cómo la tecnología puede ser utilizada para abordar problemas de salud mental?",
      "28. ¿Cuál es tu posición sobre la ética de la vigilancia y la recopilación masiva de datos por parte de gobiernos?",
      "29. ¿Cómo la tecnología puede contribuir a la preservación y conservación del medio ambiente?",
      "30. ¿Cuál es tu opinión sobre el impacto de la inteligencia artificial en la creatividad humana?",
      "31. Desde tu experiencia, ¿cómo la tecnología ha influido en la forma en que nos comunicamos emocionalmente?",
      "32. ¿Cómo la tecnología puede ser utilizada para mejorar la seguridad y privacidad en línea?",
      "33. ¿Cuál es tu visión sobre la ética de la realidad virtual en la industria del entretenimiento?",
      "34. Desde tu perspectiva, ¿cómo la tecnología puede abordar los problemas de la escasez de recursos naturales?",
      "35. ¿Cuál es tu posición sobre la ética de la inteligencia artificial en la toma de decisiones judiciales?",
      "36. ¿Cómo la tecnología puede contribuir a la investigación y resolución de problemas en la ciencia?",
      "37. ¿Qué importancia le das a la ética en la investigación y desarrollo de la tecnología?",
      "38. Desde tu experiencia, ¿cómo la tecnología ha influido en la participación ciudadana en asuntos políticos?",
      "39. ¿Cuál es tu opinión sobre el impacto de la realidad virtual en la empatía y la comprensión entre culturas?",
      "40. ¿Cómo la tecnología puede ser utilizada para mejorar la eficiencia y sostenibilidad en la agricultura?",
      "41. ¿Cuál es tu perspectiva sobre la ética de la inteligencia artificial en la creación de contenido artístico?",
      "42. Desde tu punto de vista, ¿cómo la tecnología puede abordar los desafíos de la seguridad cibernética?",
      "43. ¿Cómo la inteligencia artificial puede influir en la toma de decisiones éticas en el ámbito empresarial?",
      "44. ¿Cuál es tu visión sobre la ética de la nanotecnología en la medicina?",
      "45. Desde tu perspectiva, ¿cómo la tecnología puede ser utilizada para mejorar la atención médica en áreas remotas?",
      "46. ¿Cuál es tu posición sobre la ética de la realidad aumentada en la publicidad?",
      "47. ¿Cómo la tecnología podría abordar los desafíos de la gestión de residuos y la sostenibilidad ambiental?",
      "48. ¿Cuál es tu opinión sobre la ética de la inteligencia artificial en la toma de decisiones gubernamentales?",
      "49. Desde tu experiencia, ¿cómo la tecnología ha influido en la autonomía de los vehículos y el transporte?",
      "50. ¿Cómo la tecnología puede ser utilizada para mejorar la igualdad de género en diversos campos?",
      "51. ¿Cuál es tu perspectiva sobre la ética de la realidad virtual en la formación educativa?",
      "52. Desde tu punto de vista, ¿cómo la tecnología puede abordar los desafíos de la seguridad alimentaria global?",
      "53. ¿Cómo la inteligencia artificial puede influir en la toma de decisiones éticas en la investigación científica?",
      "54. ¿Cuál es tu visión sobre la ética de la tecnología de reconocimiento facial en la seguridad pública?",
      "55. Desde tu perspectiva, ¿cómo la tecnología ha influido en la participación ciudadana en procesos democráticos?",
      "56. ¿Cómo la tecnología puede ser utilizada para abordar los desafíos de la atención médica mental?",
      "57. ¿Cuál es tu opinión sobre la ética de la inteligencia artificial en la selección de personal?",
      "58. Desde tu experiencia, ¿cómo la tecnología ha influido en la industria del entretenimiento y los medios de comunicación?",
      "59. ¿Cómo la tecnología podría abordar los desafíos de la gestión de recursos hídricos?",
      "60. ¿Cuál es tu perspectiva sobre la ética de la realidad aumentada en entornos laborales?",
      "61. Desde tu punto de vista, ¿cómo la tecnología puede abordar los desafíos de la educación a distancia?",
      "62. ¿Cómo la inteligencia artificial puede influir en la toma de decisiones éticas en la atención médica?",
      "63. ¿Cuál es tu visión sobre la ética de la tecnología de reconocimiento biométrico en la seguridad?",
      "64. Desde tu perspectiva, ¿cómo la tecnología ha influido en la autonomía y privacidad de los usuarios en línea?",
    ],
    historia: [
      "1. ¿Cómo influye tu comprensión de la historia en tu perspectiva actual del mundo?",
      "2. Desde tu punto de vista, ¿cómo la historia puede servir como guía para decisiones futuras?",
      "3. ¿Cuál es el impacto duradero de eventos históricos en la configuración de sociedades contemporáneas?",
      "4. ¿Cuál es tu período histórico favorito y por qué te fascina?",
      "5. Desde tu perspectiva, ¿cómo la historia puede ayudarnos a comprender y abordar los desafíos actuales?",
      "6. ¿Qué lecciones importantes crees que podemos aprender de los errores del pasado?",
      "7. ¿Cómo la historia puede influir en la identidad cultural y la diversidad?",
      "8. ¿Cuál es tu opinión sobre la preservación del patrimonio histórico y cultural?",
      "9. ¿Cómo las narrativas históricas pueden ser interpretadas de manera diferente según la perspectiva cultural?",
      "10. Desde tu experiencia, ¿cómo la historia ha influido en tu percepción de la justicia y la equidad?",
      "11. ¿Cuál es tu visión sobre el papel de los museos y sitios históricos en la educación pública?",
      "12. ¿Cómo la historia puede contribuir a la construcción de una identidad nacional?",
      "13. ¿Qué eventos históricos crees que deberían recibir más atención en la educación formal?",
      "14. Desde tu perspectiva, ¿cómo la historia puede inspirar la innovación y el progreso?",
      "15. ¿Cuál es tu opinión sobre la representación histórica en medios de comunicación y entretenimiento?",
      "16. ¿Cómo la historia puede arrojar luz sobre cuestiones éticas y morales en la sociedad contemporánea?",
      "17. ¿Cuál es tu enfoque para enseñar a las generaciones futuras sobre la importancia de la historia?",
      "18. Desde tu experiencia, ¿cómo la historia ha impactado tu identidad personal y tu sentido de pertenencia?",
      "19. ¿Qué aspectos de la historia mundial te gustaría explorar más a fondo?",
      "20. ¿Cuál es tu percepción sobre la relación entre la historia y la evolución de la tecnología?",
      "21. ¿Cuál es tu perspectiva sobre cómo la historia puede influir en la diplomacia y las relaciones internacionales?",
      "22. Desde tu punto de vista, ¿cómo los movimientos sociales históricos pueden inspirar el cambio en la sociedad contemporánea?",
      "23. ¿Cuál es tu opinión sobre la enseñanza de eventos históricos controvertidos en el currículo educativo?",
      "24. ¿Cómo la historia puede contribuir a la comprensión de los conflictos étnicos y culturales actuales?",
      "25. Desde tu experiencia, ¿cómo la historia ha afectado la evolución de los derechos humanos?",
      "26. ¿Cuál es tu visión sobre la preservación y el rescate de documentos históricos y archivos?",
      "27. ¿Cómo la historia puede arrojar luz sobre los desafíos de la migración y la multiculturalidad?",
      "28. ¿Cuál es tu opinión sobre la interpretación y reinterpretación de eventos históricos a lo largo del tiempo?",
      "29. Desde tu perspectiva, ¿cómo la historia puede ser utilizada para promover la reconciliación en sociedades divididas?",
      "30. ¿Cuál es tu posición sobre la representación de figuras históricas en el arte y la cultura popular?",
      "31. ¿Cómo la historia puede ofrecer lecciones valiosas sobre la gestión de crisis y pandemias?",
      "32. Desde tu experiencia, ¿cómo la historia ha influido en la evolución de los sistemas políticos?",
      "33. ¿Cuál es tu visión sobre la contribución de las mujeres a lo largo de la historia y su representación?",
      "34. ¿Cómo la historia puede iluminar la evolución de la igualdad de género y los derechos de la mujer?",
      "35. ¿Cuál es tu opinión sobre la importancia de preservar y estudiar la historia local y regional?",
      "36. Desde tu perspectiva, ¿cómo la historia puede ayudarnos a entender la evolución de las instituciones democráticas?",
      "37. ¿Cuál es tu posición sobre la responsabilidad y ética en la representación histórica en obras de ficción?",
      "38. ¿Cómo la historia puede proporcionar perspectivas sobre la evolución de la medicina y la atención médica?",
      "39. Desde tu experiencia, ¿cómo la historia ha influido en la percepción de la identidad nacional en tu comunidad?",
      "40. ¿Cuál es tu visión sobre la conexión entre la historia y la preservación del medio ambiente?",
      "41. ¿Cómo la historia puede arrojar luz sobre la evolución de los movimientos por los derechos civiles?",
      "42. ¿Cuál es tu opinión sobre la ética de la reconstrucción y conservación de sitios históricos?",
      "43. Desde tu perspectiva, ¿cómo la historia ha influido en la percepción de la diversidad sexual y de género?",
      "44. ¿Cuál es tu posición sobre la enseñanza de múltiples perspectivas históricas en entornos educativos?",
      "45. ¿Cómo la historia puede contribuir a la comprensión de los desafíos de la globalización?",
      "46. Desde tu experiencia, ¿cómo la historia ha impactado la evolución de los derechos de las minorías étnicas?",
      "47. ¿Cuál es tu visión sobre la conexión entre la historia y la memoria colectiva en la sociedad?",
      "48. ¿Cómo la historia puede proporcionar lecciones sobre la prevención de conflictos y la promoción de la paz?",
      "49. Desde tu perspectiva, ¿cómo la historia ha influido en la formación de las estructuras económicas actuales?",
      "50. ¿Cuál es tu opinión sobre la responsabilidad de las naciones en la preservación del patrimonio histórico mundial?",
      "51. ¿Cómo la historia puede arrojar luz sobre la evolución de las relaciones internacionales y los tratados?",
      "52. Desde tu experiencia, ¿cómo la historia ha afectado la percepción de la migración y las fronteras?",
      "53. ¿Cuál es tu visión sobre la ética de la reconstrucción histórica en la arqueología?",
      "54. ¿Cómo la historia puede proporcionar perspectivas sobre la evolución de los derechos de los pueblos indígenas?",
      "55. Desde tu perspectiva, ¿cómo la historia ha influido en la evolución de los sistemas educativos?",
      "56. ¿Cuál es tu posición sobre la representación histórica de la ciencia y la medicina en los medios?",
      "57. ¿Cómo la historia puede ser utilizada para abordar la intolerancia y promover la inclusión?",
      "58. Desde tu experiencia, ¿cómo la historia ha influido en la evolución de los movimientos pacifistas?",
      "59. ¿Cuál es tu visión sobre la ética de la restitución de arte y objetos históricos a sus lugares de origen?",
      "60. ¿Cómo la historia puede proporcionar perspectivas sobre la evolución de la participación ciudadana en la toma de decisiones?",
        ],
    historiasPersonales: [
      "1. ¿Cómo crees que las historias personales pueden impactar en la percepción de los desafíos y logros?",
      "2. Desde tu perspectiva, ¿cómo las historias personales pueden contribuir a la construcción de relaciones significativas?",
      "3. ¿Cuál es tu opinión sobre la utilización de la tecnología para compartir y preservar historias personales?", 
      "4. ¿Cuál es el desafío más grande que has enfrentado y cómo te ha cambiado?",
      "5. Desde tu perspectiva, ¿cómo las historias personales pueden conectar a las personas a nivel emocional?",
      "6. ¿Cuál es tu enfoque para superar adversidades y aprender de las experiencias difíciles?",
      "7. ¿Cómo las historias personales pueden inspirar empatía y comprensión entre individuos?",
      "8. ¿Cuál es el papel de la narración de historias en la transmisión de valores familiares?",
      "9. ¿Cómo las experiencias personales pueden influir en la toma de decisiones y la formación de creencias?",
      "10. Desde tu experiencia, ¿cómo las historias personales pueden contribuir a la construcción de la identidad?",
      "11. ¿Qué aprendizajes importantes has obtenido de las historias de otras personas?",
      "12. ¿Cómo la narración de historias puede ser una herramienta poderosa para el cambio social?",
      "13. ¿Cuál es tu enfoque para compartir tus propias experiencias de vida con los demás?",
      "14. ¿Cómo las historias personales pueden impactar en la percepción de la diversidad y la inclusión?",
      "15. ¿Qué importancia le das a la autenticidad al contar tus propias historias personales?",
      "16. ¿Cuál es tu visión sobre el equilibrio entre la privacidad y la apertura al compartir experiencias personales?",
      "17. ¿Cómo las historias personales pueden influir en la empatía hacia las experiencias de los demás?",
      "18. Desde tu perspectiva, ¿cómo las historias personales pueden contribuir a la construcción de comunidades fuertes?",
      "19. ¿Cómo afecta la retroalimentación positiva o negativa a la narración de tus propias historias personales?",
      "20. ¿Cuál es tu enfoque para preservar y compartir tus experiencias personales para las futuras generaciones?",
      "21. ¿Cómo la reflexión sobre tus propias historias personales ha influido en tus metas y aspiraciones?",
      "22. Desde tu perspectiva, ¿cómo las historias personales pueden proporcionar lecciones valiosas sobre el crecimiento personal?",
      "23. ¿Cuál es tu experiencia más memorable al compartir historias personales con otras personas?",
      "24. ¿Cómo la escritura de tus propias historias personales ha sido terapéutica o transformadora para ti?",
      "25. Desde tu experiencia, ¿cómo las historias personales pueden ayudar a superar estigmas y prejuicios?",
      "26. ¿Cuál es tu enfoque para equilibrar la honestidad y la protección de la privacidad al compartir experiencias personales?",
      "27. ¿Cómo las historias personales pueden ser una fuente de inspiración para enfrentar desafíos similares?",
      "28. ¿Cuál es tu opinión sobre la representación de historias personales en diferentes formas de medios?",
      "29. Desde tu perspectiva, ¿cómo las historias personales pueden influir en la percepción de la resiliencia?",
      "30. ¿Cuál es tu enfoque para transmitir valores familiares a través de historias personales?",
      "31. ¿Cómo las historias personales pueden servir como puentes culturales y promover la comprensión intercultural?",
      "32. Desde tu experiencia, ¿cómo las historias personales han afectado tus relaciones más cercanas?",
      "33. ¿Cuál es tu visión sobre el impacto de las historias personales en la autoaceptación y la autoestima?",
      "34. ¿Cómo la escucha activa de las historias personales de los demás puede fortalecer la empatía?",
      "35. ¿Cuál es tu opinión sobre la representación de la diversidad en las narrativas de historias personales?",
      "36. Desde tu perspectiva, ¿cómo las historias personales pueden influir en la percepción del éxito?",
      "37. ¿Cuál es tu experiencia al enfrentar la vulnerabilidad al compartir historias personales?",
      "38. ¿Cómo las historias personales pueden ser herramientas efectivas para la educación y el aprendizaje?",
      "39. Desde tu experiencia, ¿cómo las historias personales pueden ayudar a superar la adversidad?",
      "40. ¿Cuál es tu enfoque para preservar las tradiciones familiares a través de historias personales?",
      "41. ¿Cómo las historias personales pueden contribuir a la construcción de un sentido de pertenencia?",
      "42. Desde tu perspectiva, ¿cómo las historias personales pueden desafiar y cambiar percepciones erróneas?",
      "43. ¿Cuál es tu opinión sobre el papel de la emoción en la narración efectiva de historias personales?",
      "44. ¿Cómo las historias personales pueden ser utilizadas para promover la compasión y la empatía en la sociedad?",
      "45. Desde tu experiencia, ¿cómo las historias personales han influido en tu capacidad para superar desafíos?",
      "46. ¿Cuál es tu enfoque para equilibrar la autenticidad y la selección de detalles al compartir historias personales?",
      "47. ¿Cómo las historias personales pueden ser utilizadas para abordar problemas sociales y promover el cambio?",
      "48. Desde tu perspectiva, ¿cómo las historias personales pueden influir en la toma de decisiones importantes?",
      "49. ¿Cuál es tu opinión sobre la representación de historias personales en el ámbito de la salud mental?",
      "50. ¿Cómo las historias personales pueden ayudar a construir puentes entre diferentes generaciones?",
      "51. Desde tu experiencia, ¿cómo las historias personales han influido en tu autoconocimiento?",
      "52. ¿Cuál es tu enfoque para compartir historias personales que contienen lecciones de fracasos?",
      "53. ¿Cómo las historias personales pueden ser utilizadas para promover la comprensión y el apoyo en comunidades diversas?",
      "54. Desde tu perspectiva, ¿cómo las historias personales pueden afectar la percepción de la identidad cultural?",
      "55. ¿Cuál es tu opinión sobre la representación de historias personales en las redes sociales?",
      "56. ¿Cómo las historias personales pueden ser utilizadas para fomentar la empatía hacia experiencias diferentes a las propias?",
      "57. Desde tu experiencia, ¿cómo las historias personales pueden contribuir a la construcción de una narrativa de vida coherente?",
      "58. ¿Cuál es tu enfoque para mantener la autenticidad al compartir historias personales en entornos profesionales?",
      "59. ¿Cómo las historias personales pueden ser herramientas efectivas para la sensibilización sobre problemas sociales?",
      "60. Desde tu perspectiva, ¿cómo las historias personales pueden influir en la percepción de la salud mental?",
    ],
    miedos: [
      "1. ¿Cómo manejas los miedos que surgen en situaciones de cambio o incertidumbre?",
      "2. Desde tu perspectiva, ¿cómo influye la autoconciencia en la identificación y superación de los miedos?",
      "3. ¿Qué estrategias utilizas para afrontar miedos que pueden surgir en el ámbito profesional?",
      "4. ¿Cómo identificas y reconoces tus miedos personales?",
      "5. ¿Crees que la exposición gradual a los miedos puede ayudar a superarlos?",
      "6. ¿Cómo influyen los miedos en la toma de decisiones importantes en tu vida?",
      "7. ¿Cuál es tu enfoque para ayudar a otros a superar sus miedos?",
      "8. ¿Cómo los miedos pueden ser una fuente de motivación o limitación en tu vida?",
      "9. ¿Hay algún miedo que hayas superado y que haya tenido un impacto significativo en tu crecimiento personal?",
      "10. ¿Cómo manejas los miedos irracionales que pueden surgir en situaciones cotidianas?",
      "11. ¿Qué consejos tienes para aquellos que luchan contra miedos similares a los tuyos?",
      "12. ¿Cómo influyen los miedos en tus relaciones personales y profesionales?",
      "13. ¿Crees que los miedos pueden cambiar con el tiempo y la experiencia?",
      "14. ¿Cuál es tu perspectiva sobre la relación entre la valentía y la gestión de los miedos?",
      "15. ¿Cómo afecta el reconocimiento de tus miedos a tu autoestima y confianza?",
      "16. ¿Crees que compartir tus miedos con otros puede fortalecer las conexiones interpersonales?",
      "17. ¿Cuál es tu enfoque para ayudar a los demás a superar miedos profundamente arraigados?",
      "18. ¿Qué papel juega la aceptación en la gestión de los miedos?",
      "19. ¿Cómo los miedos pueden afectar tus metas y aspiraciones a largo plazo?",
      "20. ¿Cuál es tu consejo para enfrentar miedos desconocidos o situaciones nuevas?",
      "21. ¿Cómo el miedo ha influido en tus elecciones profesionales y en la búsqueda de tu vocación?",
      "22. Desde tu perspectiva, ¿cómo los miedos pueden ser aprendizajes importantes en la vida?",
      "23. ¿Qué estrategias utilizas para enfrentar los miedos que están relacionados con el juicio social?",
      "24. ¿Cómo los miedos pueden manifestarse de manera diferente en situaciones personales y laborales?",
      "25. Desde tu experiencia, ¿cómo los miedos pueden afectar la salud mental y emocional?",
      "26. ¿Crees que la expresión artística puede ser una vía para explorar y superar los miedos?",
      "27. ¿Cuál es tu enfoque para manejar los miedos relacionados con el cambio?",
      "28. ¿Cómo influyen los miedos en la toma de riesgos en tu vida?",
      "29. ¿Hay algún libro, película o experiencia cultural que haya abordado los miedos de manera impactante para ti?",
      "30. ¿Cómo los miedos pueden afectar las decisiones financieras y la planificación del futuro?",
      "31. Desde tu perspectiva, ¿cómo se pueden transformar los miedos en oportunidades de crecimiento?",
      "32. ¿Qué importancia le das a la autoempatía al enfrentar tus miedos?",
      "33. ¿Cómo los miedos pueden afectar la percepción del tiempo y la planificación a largo plazo?",
      "34. ¿Cuál es tu experiencia al ayudar a otros a confrontar miedos relacionados con experiencias pasadas?",
      "35. ¿Crees que los miedos pueden ser heredados o aprendidos principalmente a través de experiencias?",
      "36. Desde tu experiencia, ¿cómo los miedos pueden afectar las relaciones familiares?",
      "37. ¿Cuál es tu enfoque para superar miedos que están arraigados en experiencias de la infancia?",
      "38. ¿Cómo los miedos pueden influir en la toma de decisiones impulsivas o cautelosas?",
      "39. ¿Hay alguna actividad o práctica específica que encuentres útil para gestionar tus miedos?",
      "40. ¿Cómo los miedos pueden afectar la autoimagen y la construcción de la identidad personal?",
      "41. Desde tu perspectiva, ¿cómo los miedos pueden ser percibidos de manera diferente en diversas culturas?",
      "42. ¿Cuál es tu experiencia al enfrentar miedos relacionados con el rendimiento y la competencia?",
      "43. ¿Crees que los miedos pueden ser un motor para la creatividad y la innovación?",
      "44. ¿Cómo influyen los miedos en la toma de decisiones éticas en tu vida?",
      "45. Desde tu experiencia, ¿cómo los miedos pueden afectar la calidad del sueño y la salud física?",
      "46. ¿Cuál es tu enfoque para enfrentar miedos relacionados con la soledad o el aislamiento?",
      "47. ¿Cómo los miedos pueden influir en la adopción de hábitos saludables o perjudiciales?",
      "48. ¿Crees que los miedos pueden ser un catalizador para la autoexploración y el autoconocimiento?",
      "49. ¿Hay algún lugar o entorno específico que despierte tus miedos de manera más pronunciada?",
      "50. ¿Cómo los miedos pueden influir en la toma de decisiones importantes en las relaciones amorosas?",
      "51. Desde tu perspectiva, ¿cómo los miedos pueden impactar la productividad y la consecución de metas?",
      "52. ¿Cuál es tu experiencia al enfrentar miedos relacionados con la tecnología y la conectividad constante?",
      "53. ¿Cómo los miedos pueden afectar las decisiones sobre la participación en actividades sociales?",
      "54. ¿Crees que la espiritualidad o la práctica religiosa puede ser una fuente para abordar los miedos?",
      "55. Desde tu experiencia, ¿cómo los miedos pueden influir en la capacidad para confiar en los demás?",
      "56. ¿Cuál es tu enfoque para enfrentar miedos relacionados con el envejecimiento y la mortalidad?",
      "57. ¿Cómo los miedos pueden afectar la toma de decisiones en el ámbito académico o profesional?",
      "58. ¿Hay alguna actividad específica que encuentres reconfortante al enfrentar tus miedos?",
      "59. ¿Desde tu perspectiva, cómo los miedos pueden influir en la percepción de la felicidad?",
      "60. ¿Cuál es tu experiencia al enfrentar miedos relacionados con la expresión y comunicación emocional?",
    ],
    amor: [
    "1. ¿Cómo influyen tus experiencias familiares en tu percepción del amor?",
    "2. Desde tu perspectiva, ¿cómo el amor contribuye al crecimiento personal y la autoaceptación?",
    "3. ¿Qué importancia le das a la compatibilidad en una relación amorosa?",
    "4. ¿Cómo ha evolucionado tu concepto de amor a lo largo del tiempo?",
    "5. Desde tu perspectiva, ¿cómo influye el amor en la toma de decisiones importantes en tu vida?",
    "6. ¿Qué lecciones has aprendido de relaciones pasadas en términos de amor y compatibilidad?",
    "7. ¿Cómo afecta el amor a tu bienestar emocional y mental?",
    "8. ¿Cuál es tu opinión sobre las diferentes formas de expresar y recibir amor?",
    "9. ¿Cómo manejas los desafíos y conflictos en una relación amorosa?",
    "10. ¿Cuál es tu visión sobre el equilibrio entre el amor propio y el amor hacia los demás?",
    "11. ¿Crees en el concepto de 'almas gemelas' o crees que el amor es una construcción continua?",
    "12. ¿Cómo influye la cultura y la sociedad en tu comprensión del amor?",
    "13. ¿Cuál es tu enfoque para mantener viva la chispa del amor en una relación a largo plazo?",
    "14. ¿Cómo el amor puede ser una fuente de inspiración y motivación en tu vida?",
    "15. ¿Qué importancia le das a la comunicación en una relación amorosa exitosa?",
    "16. ¿Cómo influyen las experiencias familiares en tu percepción y búsqueda del amor?",
    "17. ¿Cuál es tu opinión sobre la compatibilidad en una relación amorosa?",
    "18. ¿Cómo el amor puede contribuir al crecimiento personal y la autoaceptación?",
    "19. ¿Cuál es tu consejo para aquellos que buscan un amor duradero y significativo?",
    "20. ¿Cómo crees que el amor puede impactar en la sociedad en general?",
    "21. ¿Cómo influyen las expectativas culturales en tu percepción de las relaciones amorosas?",
    "22. Desde tu perspectiva, ¿cómo se puede cultivar la intimidad emocional en una relación?",
    "23. ¿Qué importancia le das al perdón y la tolerancia en una relación de pareja?",
    "24. ¿Cómo manejas las diferencias y los desafíos en una relación amorosa?",
    "25. Desde tu experiencia, ¿cómo el amor puede influir en la toma de decisiones profesionales?",
    "26. ¿Cuál es tu opinión sobre las relaciones a larga distancia y cómo afectan al amor?",
    "27. ¿Cómo el amor puede ser una fuente de fortaleza durante momentos difíciles?",
    "28. ¿Qué papel juega la confianza en la construcción y mantenimiento del amor?",
    "29. ¿Cuál es tu enfoque para mantener un equilibrio entre la individualidad y la vida en pareja?",
    "30. ¿Cómo influyen las relaciones amorosas en la percepción de la felicidad y el bienestar general?",
    "31. Desde tu perspectiva, ¿cómo se pueden superar las crisis en una relación amorosa?",
    "32. ¿Qué aprendizajes importantes has obtenido de experiencias de amor no correspondido?",
    "33. ¿Cómo el amor puede influir en la toma de decisiones sobre el compromiso y el matrimonio?",
    "34. ¿Cuál es tu opinión sobre el impacto de las redes sociales en las relaciones amorosas?",
    "35. ¿Cómo manejas la independencia emocional mientras estás en una relación amorosa?",
    "36. ¿Desde tu experiencia, cómo el amor puede ser una fuerza de cambio y crecimiento personal?",
    "37. ¿Cuál es tu enfoque para mantener la llama del romance en una relación a largo plazo?",
    "38. ¿Cómo influye la autoestima en la capacidad para dar y recibir amor?",
    "39. ¿Qué importancia le das a la planificación del futuro en una relación amorosa?",
    "40. ¿Cómo el amor puede afectar la percepción del tiempo y la duración de una relación?",
    "41. Desde tu perspectiva, ¿cómo el amor puede ser una fuente de motivación en la vida cotidiana?",
    "42. ¿Cuál es tu opinión sobre las relaciones abiertas o no convencionales?",
    "43. ¿Cómo influyen las experiencias pasadas en la disposición a comprometerse en una nueva relación?",
    "44. ¿Desde tu experiencia, cómo se puede mantener viva la amistad en una relación amorosa?",
    "45. ¿Cuál es tu visión sobre el impacto del amor en la toma de decisiones parentales?",
    "46. ¿Cómo influye el amor en la percepción de la propia identidad dentro de una relación?",
    "47. ¿Qué importancia le das a la independencia y la autonomía en una relación amorosa?",
    "48. ¿Desde tu perspectiva, cómo influye el amor en la toma de decisiones financieras compartidas?",
    "49. ¿Cuál es tu enfoque para superar la rutina y mantener la frescura en una relación a largo plazo?",
    "50. ¿Cómo el amor puede ser una fuente de apoyo durante momentos de cambio y transición?",
    "51. Desde tu experiencia, ¿cómo influyen las relaciones familiares en la construcción del amor propio?",
    "52. ¿Cuál es tu opinión sobre el equilibrio entre el dar y recibir en una relación amorosa?",
    "53. ¿Cómo el amor puede ser una fuente de inspiración para metas y proyectos compartidos?",
    "54. ¿Cómo manejas las diferencias de valores y creencias en una relación amorosa?",
    "55. Desde tu perspectiva, ¿cómo afecta el amor a la percepción del éxito personal?",
    "56. ¿Cuál es tu enfoque para enfrentar desafíos culturales o de origen en una relación amorosa?",
    "57. ¿Cómo influye el amor en la capacidad para superar la adversidad y los obstáculos?",
    "58. ¿Desde tu experiencia, cómo el amor puede ser una fuente de resiliencia emocional?",
    "59. ¿Cuál es tu opinión sobre la influencia de la pasión en una relación amorosa?",
    "60. ¿Cómo el amor puede influir en la toma de decisiones sobre la parentalidad y la crianza de los hijos?",
    ],
    negocios: [
      "1. ¿Cómo defines el éxito empresarial y qué medidas tomas para alcanzarlo?",
      "2. Desde tu perspectiva, ¿cuál es la importancia de la innovación en el mundo de los negocios?",
      "3. ¿Cómo manejas la toma de decisiones éticas en tu empresa?",
      "4. ¿Cuál es tu opinión sobre la responsabilidad social corporativa y cómo la integras en tu negocio?",
      "5. Desde tu experiencia, ¿cómo la cultura organizacional impacta en el rendimiento de una empresa?",
      "6. ¿Cuál es tu enfoque para fomentar la diversidad e inclusión en el lugar de trabajo?",
      "7. ¿Cómo abordas la gestión del cambio en un entorno empresarial?",
      "8. ¿Cuál es tu visión sobre el equilibrio entre la automatización y la preservación de empleos?",
      "9. ¿Cómo defines y fomentas la colaboración efectiva entre los equipos en tu organización?",
      "10. Desde tu perspectiva, ¿cuál es el papel de la ética en la toma de decisiones empresariales?",
      "11. ¿Cómo manejas la competencia en el mercado y qué estrategias empleas para destacar?",
      "12. ¿Cuál es tu enfoque para construir y mantener relaciones sólidas con los clientes?",
      "13. ¿Cómo influye la transformación digital en tu estrategia empresarial?",
      "14. Desde tu experiencia, ¿cómo se pueden abordar los desafíos de la cadena de suministro?",
      "15. ¿Cuál es tu opinión sobre la sostenibilidad en el ámbito empresarial?",
      "16. ¿Cómo enfrentas los momentos de crisis empresarial y qué aprendizajes obtienes?",
      "17. ¿Cuál es tu perspectiva sobre la relación entre la cultura empresarial y la agilidad organizativa?",
      "18. Desde tu punto de vista, ¿cómo se puede fomentar la creatividad y la innovación en equipos?",
      "19. ¿Cómo abordas la toma de riesgos en la toma de decisiones empresariales?",
      "20. ¿Cuál es tu estrategia para atraer y retener talento en tu empresa?",
      "21. ¿Cómo la inteligencia artificial y el análisis de datos influyen en tus estrategias de negocio?",
      "22. Desde tu experiencia, ¿cómo se pueden equilibrar los objetivos financieros y sociales en una empresa?",
      "23. ¿Cuál es tu enfoque para manejar las relaciones con socios y aliados comerciales?",
      "24. ¿Cómo afecta la globalización a tu estrategia empresarial?",
      "25. ¿Cuál es tu visión sobre el papel de la ética en la publicidad y el marketing?",
      "26. Desde tu perspectiva, ¿cómo se pueden superar los desafíos de la ciberseguridad empresarial?",
      "27. ¿Cuál es tu opinión sobre el impacto de las redes sociales en las estrategias de marca?",
      "28. ¿Cómo manejas la adaptabilidad en un entorno empresarial cambiante?",
      "29. ¿Cuál es tu estrategia para mantener la calidad del producto o servicio a lo largo del tiempo?",
      "30. Desde tu experiencia, ¿cómo la gestión del tiempo afecta la productividad empresarial?",
      "31. ¿Cómo evalúas y gestionas la satisfacción del cliente en tu empresa?",
      "32. ¿Cuál es tu enfoque para la toma de decisiones financieras y la gestión del presupuesto?",
      "33. ¿Cómo manejas la presión y el estrés en el ámbito empresarial?",
      "34. ¿Cuál es tu visión sobre el equilibrio entre la rentabilidad y la responsabilidad social?",
      "35. Desde tu perspectiva, ¿cómo la tecnología emergente puede transformar tu industria?",
      "36. ¿Cómo abordas la formación y el desarrollo de habilidades en tu equipo?",
      "37. ¿Cuál es tu opinión sobre la implementación de estrategias ecológicas en la cadena de suministro?",
      "38. Desde tu experiencia, ¿cómo la agilidad empresarial puede ser clave en entornos volátiles?",
      "39. ¿Cómo influye la cultura de trabajo remoto en la dinámica empresarial?",
      "40. ¿Cuál es tu estrategia para mantener la lealtad del cliente en un mercado competitivo?",
      "41. ¿Cómo manejas las crisis de relaciones públicas y qué aprendizajes obtienes?",
      "42. Desde tu perspectiva, ¿cómo se pueden abordar los problemas de ética en la inteligencia artificial empresarial?",
      "43. ¿Cuál es tu enfoque para la mejora continua en la calidad del producto o servicio?",
      "44. ¿Cómo la diversidad de pensamiento en tu equipo contribuye a la toma de decisiones?",
      "45. ¿Cuál es tu visión sobre la integración de la sostenibilidad en modelos de negocio tradicionales?",
      "46. Desde tu experiencia, ¿cómo se pueden gestionar eficazmente los equipos virtuales?",
      "47. ¿Cómo afecta la gestión de la cadena de suministro a la eficiencia operativa de tu empresa?",
      "48. ¿Cuál es tu opinión sobre la automatización de procesos y su impacto en el empleo?",
      "49. ¿Cómo manejas la comunicación interna para garantizar la alineación de objetivos?",
      "50. Desde tu perspectiva, ¿cómo se pueden establecer y medir metas efectivas en una empresa?",
      "51. ¿Cuál es tu estrategia para mantener la ética en la toma de decisiones financieras?",
      "52. ¿Cómo influye la cultura de la empresa en la retención de empleados y el compromiso?",
      "53. ¿Cuál es tu opinión sobre la inteligencia emocional en el liderazgo empresarial?",
      "54. Desde tu experiencia, ¿cómo abordas la gestión de conflictos dentro de tu equipo?",
      "55. ¿Cómo se pueden utilizar los datos para mejorar la eficiencia operativa en tu organización?",
      "56. ¿Cuál es tu enfoque para mantener un equilibrio entre la rentabilidad y la responsabilidad ambiental?",
      "57. Desde tu perspectiva, ¿cómo la transparencia empresarial puede construir la confianza del cliente?",
      "58. ¿Cómo manejas la toma de decisiones en situaciones de incertidumbre económica?",
      "59. ¿Cuál es tu estrategia para fomentar la creatividad y la innovación en todos los niveles de la empresa?",
      "60. Desde tu experiencia, ¿cómo la agilidad organizativa puede ser crucial para la supervivencia empresarial en un entorno competitivo?"
    ],
    educacion: [
     "1. ¿Cómo defines la calidad educativa y qué medidas tomas para mejorarla?",
      "2. Desde tu perspectiva, ¿cuál es el papel de la tecnología en la educación del siglo XXI?",
      "3. ¿Cómo abordas la equidad y la inclusión en el entorno educativo?",
      "4. ¿Cuál es tu opinión sobre la evaluación del rendimiento escolar y cómo puede mejorarse?",
      "5. Desde tu experiencia, ¿cómo la educación puede adaptarse a diferentes estilos de aprendizaje?",
      "6. ¿Cuál es tu enfoque para fomentar la creatividad y la innovación en el aula?",
      "7. ¿Cómo manejas los desafíos de la enseñanza a distancia y la educación virtual?",
      "8. ¿Cuál es tu visión sobre el equilibrio entre la educación tradicional y las metodologías modernas?",
      "9. ¿Cómo influye la participación de los padres en el éxito educativo de los estudiantes?",
      "10. Desde tu perspectiva, ¿cuál es el impacto de las artes y la música en la educación?",
      "11. ¿Cómo abordas la enseñanza de habilidades socioemocionales en el currículo escolar?",
      "12. ¿Cuál es tu opinión sobre la presión académica y su impacto en la salud mental de los estudiantes?",
      "13. Desde tu experiencia, ¿cómo se pueden abordar las brechas educativas entre distintas comunidades?",
      "14. ¿Cuál es tu enfoque para fomentar el pensamiento crítico y la resolución de problemas?",
      "15. ¿Qué importancia le das a la educación STEM (ciencia, tecnología, ingeniería y matemáticas) en el currículo?",
      "16. ¿Cómo manejas la diversidad cultural en el aula y promueves la comprensión intercultural?",
      "17. ¿Cuál es tu visión sobre la educación global y su impacto en la ciudadanía mundial?",
      "18. Desde tu perspectiva, ¿cómo la educación puede preparar a los estudiantes para el mundo laboral?",
      "19. ¿Cómo evalúas el éxito educativo más allá de las calificaciones académicas?",
      "20. ¿Cuál es tu estrategia para motivar a los estudiantes y fomentar el amor por el aprendizaje?",
      "21. ¿Cuál es tu opinión sobre la educación a lo largo de toda la vida y el aprendizaje continuo?",
      "22. Desde tu experiencia, ¿cómo se pueden abordar los desafíos de la educación inclusiva?",
      "23. ¿Cuál es tu enfoque para integrar la educación ambiental en el plan de estudios?",
      "24. ¿Cómo manejas la introducción de nuevas tecnologías educativas en el proceso de enseñanza?",
      "25. ¿Cuál es tu visión sobre la importancia de la educación en habilidades financieras?",
      "26. Desde tu perspectiva, ¿cómo se puede mejorar la formación docente?",
      "27. ¿Cómo abordas la educación en valores y ética en el entorno escolar?",
      "28. ¿Cuál es tu estrategia para enfrentar el bullying y promover un ambiente escolar seguro?",
      "29. ¿Cómo influye la participación de la comunidad en el éxito de las instituciones educativas?",
      "30. Desde tu experiencia, ¿cómo la educación puede contribuir a la igualdad de género?",
      "31. ¿Cuál es tu opinión sobre la implementación de la educación a distancia en el futuro?",
      "32. ¿Cómo manejas la adaptación de la educación a las necesidades individuales de los estudiantes?",
      "33. ¿Qué importancia le das a la educación artística en el desarrollo integral de los estudiantes?",
      "34. ¿Cuál es tu visión sobre la educación en habilidades sociales y emocionales?",
      "35. Desde tu perspectiva, ¿cómo se pueden integrar las nuevas tecnologías sin dejar a nadie atrás?",
      "36. ¿Cómo abordas la educación en temas de salud mental y bienestar emocional?",
      "37. ¿Cuál es tu enfoque para involucrar a los estudiantes en el proceso de toma de decisiones escolares?",
      "38. Desde tu experiencia, ¿cómo se pueden abordar las desigualdades en el acceso a la educación?",
      "39. ¿Cuál es tu estrategia para fomentar la autonomía y la responsabilidad en los estudiantes?",
      "40. ¿Cómo manejas la educación a distancia de manera efectiva?",
      "41. ¿Cuál es tu opinión sobre la importancia de la educación en habilidades de pensamiento computacional?",
      "42. Desde tu perspectiva, ¿cómo se pueden abordar las barreras lingüísticas en la educación?",
      "43. ¿Cuál es tu enfoque para evaluar y mejorar la eficacia de los programas educativos?",
      "44. ¿Cómo manejas la inclusión de personas con discapacidades en el entorno educativo?",
      "45. ¿Cuál es tu visión sobre el equilibrio entre la preparación académica y las habilidades prácticas en la educación?",
      "46. Desde tu experiencia, ¿cómo se pueden abordar los problemas de desmotivación escolar?",
      "47. ¿Cómo influye la educación en la formación del carácter y la ciudadanía de los estudiantes?",
      "48. ¿Cuál es tu opinión sobre la educación basada en competencias?",
      "49. ¿Cómo manejas la introducción de enfoques pedagógicos innovadores en el aula?",
      "50. Desde tu perspectiva, ¿cómo puede la educación contribuir a la resolución de problemas sociales?",
      "51. ¿Cuál es tu estrategia para fomentar la participación activa de los estudiantes en el aprendizaje?",
      "52. ¿Cómo abordas la educación en temas de diversidad e inclusión?",
      "53. ¿Qué importancia le das a la educación en el desarrollo de habilidades de liderazgo?",
      "54. Desde tu experiencia, ¿cómo se pueden integrar la educación artística y la educación STEM?",
      "55. ¿Cuál es tu visión sobre la educación en valores cívicos y responsabilidad ciudadana?",
      "56. ¿Cómo manejas la educación en temas de cambio climático y sostenibilidad?",
      "57. ¿Cuál es tu opinión sobre la evaluación continua frente a los exámenes tradicionales?",
      "58. Desde tu perspectiva, ¿cómo la educación puede preparar a los estudiantes para la era digital?",
      "59. ¿Cómo influye la educación en la formación de la identidad cultural de los estudiantes?",
      "60. Desde tu experiencia, ¿cómo se pueden abordar los desafíos de la educación en entornos socioeconómicos desfavorecidos?",
    ],
    
};



// Ruta del archivo de audio
const audioUrl = "audio_boton_siguiente.mp3"; // Reemplaza con la ruta correcta de tu archivo de audio

// Función para mostrar la siguiente pregunta
function nextQuestion() {
  const randomThemeIndex = Math.floor(Math.random() * themes.length);
  const randomTheme = themes[randomThemeIndex];
  const randomQuestionIndex = Math.floor(Math.random() * questions[randomTheme].length);

  // Muestra la categoría y la pregunta en el contenedor
  const categoryElement = document.getElementById('category');
  const questionElement = document.getElementById('question');

  categoryElement.className = `category ${randomTheme}`;
  categoryElement.innerHTML = capitalizeFirstLetter(randomTheme);

  questionElement.innerHTML = questions[randomTheme][randomQuestionIndex];
  questionElement.style.setProperty('--category-color', getComputedStyle(categoryElement).color);

  // Reproduce el audio
  playAudio();
}

// Función para reproducir el audio
function playAudio() {
  const audio = new Audio(audioUrl);
  audio.play();
}

// Función para capitalizar la primera letra de una cadena
function capitalizeFirstLetter(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}